### ISSUE TITLE
settings.toml not found

### ISSUE THREAD

**Issue by maziarmzh** [hueyyeng/AssetsBrowser#17]
hi
when i try running  assetsbrowser.py ,raise an error settings.toml not found.

please advise
tanx

**Comment by hueyyeng** [comment]
It's been awhile since I last update this repo but I believe `settings.toml` needs to be created manually in the **config** folder.

Just create one and see how it behaves.

**Comment by maziarmzh** [comment]
Thank you for your respond.

I did create `setting.toml ` manually and here is the result:
```

C:\python3\python.exe "K:/Pycharm/assetsbrowser.py"
Traceback (most recent call last):
  File "K:/Pycharm/assetsbrowser.py", line 18, in <module>
    from helpers.widgets import ColumnViewWidget
  File "K:\Pycharm\helpers\widgets.py", line 16, in <module>
    ICON_THUMBNAILS_MODE = IconRadio(get_setting('Advanced', 'IconThumbnails'))
  File "K:\Pycharm\config\configurations.py", line 112, in get_setting
    value = config[section][setting]
KeyError: 'Advanced'

Process finished with exit code 1
```
tested with python 3.6.7

**Comment by hueyyeng** [comment]
As I don't have any plan to continue working on this repo, can you try copy paste the following into the `settings.toml`

```toml
[Settings]
ProjectPath = "P:/"
ShowDescriptionPanel = true
CurrentProject = "DQ"

[UI]
Font = "sans-serif"
FontMode = -2
FontSize = 12
Theme = "LIGHT"

[Assets]
UsePrefix = true
PrefixType = -2
UseSuffix = true
SuffixType = -2
SuffixVersionMode = 0
SuffixCustomName = "ver"
MaxChars = 3
Separator = "UNDERSCORE"
CategoryList = [ "BG", "CH", "FX", "Props", "Vehicles",]
SubfolderList = [ "References", "Scenes", "Textures", "WIP",]

[Advanced]
Preview = -3
PreviewCustomMaxSize = 400
IconThumbnails = -4
UseDebugLog = false

```

You will need to change some stuff here and there depending on the Python traceback error but that is what I have right now on my PC and it works.
